### ISSUE TITLE
Proposal: strict.yaml

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/lints#102]
A stricter version of rules (`strict.yaml` extending `recommended.yaml`) would be very interesting.

Here we need to add in our projects some extra rules to catch some possible bugs:

```yaml
linter:
  rules:
    - avoid_dynamic_calls
    - avoid_type_to_string
    - no_runtimeType_toString
    - discarded_futures
    - no_adjacent_strings_in_list
```

I understand that the rules above shouldn't be in `recommended.yaml`. Specially `dynamic` calls, that are part of the dart language. But for a production software we need them to catch some possible bugs, and when a `dynamic` call is need we explicitly add an `ignore` directive in the code.
